### ISSUE TITLE
Artisan Cookbook is displayed despite not being an actual item

### ISSUE THREAD

**Issue by Gogo1951** [BrenoLudgero/Recipe_Master#10]
<img width="380" alt="image" src="https://github.com/user-attachments/assets/e3802644-0583-4ebc-a6ec-dd4c84f96a25">

Having things in here like this throws off the count. It's annoying for completionist people who want to see 100%. Ha. (=

**Comment by BrenoLudgero** [comment]
Hello, @Gogo1951.

During the scraping processes many unavailable item are filtered to achieve that goal.
The Artisan Cookbook, however, was purposefully included to allow you to track you next skill-up goal and to check how to unlock the next level of cooking.

Rest assured that as soon as your character becomes an artisan cook the item will be marked as learned and the count will be increased by one.
