### ISSUE TITLE
Inaccurate resutls in tooltips

### ISSUE THREAD

**Issue by Gogo1951** [BrenoLudgero/Recipe_Master#15]
Hey I'm seeing some inaccurate results now in the tooltips. How do I prevent this?

When I'm on my Warlock, it tells me my Paladin can learn this. (Note that ATT recognizes that it's learned on the Paladin. And I have opened cooking profession on all toons since installing Recipe Master.)

<img width="473" alt="image" src="https://github.com/user-attachments/assets/f5f6877d-fb80-47ba-8634-136d033078e2">

But then when I log into paladin it says already known.

<img width="776" alt="image" src="https://github.com/user-attachments/assets/fd13729d-6acf-4d82-a4fb-5a3d0dc5c305">

I really want to get rid of All The Things, since the only thing I use it for is recipe tracking and it's got a massive footprint. Just need to know the tooltips are accurate. How can I ensure this?

**Comment by BrenoLudgero** [comment]
Hello, @Gogo1951.

I've learned a few new recipes (including Longjaw Mud Snapper) in an attempt to reproduce the issue but the recipes have been correctly detected as learned in the tooltip.

![Recipe learned by Riff](https://github.com/user-attachments/assets/5a41c3ff-c430-4309-9964-b7b82059eaa0)

![Riff is present in the recipe's tooltip](https://github.com/user-attachments/assets/40d3366a-1e4f-4d5f-ae8f-d433fa82c589)

Could you please open the cooking window in your Paladin and check if his/her name becomes present in the tooltip?

**Comment by Gogo1951** [comment]
Yeah, when I go through and re-open cooking on all my toons, it does fix it. I just don't know how it got off in the first place. I'll keen an eye out! Thanks!

**Comment by BrenoLudgero** [comment]
Great!

To prevent this from happening again, make sure to open the respective profession window after learning a new recipe / skill. This is, unfortunately, required to recognize what skills the character have learned.

I'll add this information in the add-on description.

Thank you for your feedback, @Gogo1951!
