### ISSUE TITLE
Detect new skills as soon as they are learned

### ISSUE THREAD

**Issue by Gogo1951** [BrenoLudgero/Recipe_Master#16]
I finally figured out what was causing the issue I mentioned earlier (#15). 

It turns out that I wasn’t always opening my profession after learning a recipe -- I would just train the ability and move on. In Recipe Master, a recipe doesn’t get marked as “known” until you open the profession window. This was creating all sorts of strange problems for me.

By comparison, ATT seems to add items both when you learn them and when you open the profession, which feels a lot more intuitive. It might be worth considering that approach for better usability.

Anyway, that’s what was behind the data gaps I was seeing earlier.

(Tested this in Classic Era, if that’s relevant!)

Cheers!

**Comment by BrenoLudgero** [comment]
Hello, @Gogo1951.

Your newly learned skills are now detected without having to open the respective profession window in version 2.4.3.

Thank you for your suggestion!

**Comment by Gogo1951** [comment]
Awesome, thanks mate!
