### ISSUE TITLE
BigWigsMods Packager

### ISSUE THREAD

**Issue by Gogo1951** [BrenoLudgero/Recipe_Master#17]
Hey mate, do you want a hand setting up BigWigsMods Packager with GitHub actions? Makes doing builds and deploying them to CurseForge / et al really easy! Just ping me, we can set it up in no time. (=

Gogo1951 on Discord.

**Comment by BrenoLudgero** [comment]
Hello, @Gogo1951.

I'll definitely do that but please, reserve this space for issues related to the add-on's operation.
