### ISSUE TITLE
TradeSkillMaster compatibility

### ISSUE THREAD

**Issue by Myrroddin** [BrenoLudgero/Recipe_Master#2]
Looking at [TSM's addon API](https://api.tradeskillmaster.com/addon/), there is this useful API call: `TSM_API.IsUIVisible("CRAFTING")` I suggest checking for that, then displaying Recipe Master's list of recipes either attached to TSM's crafting UI on the top left or top right, as per user preference. I think defaulting to the top right would look the best.

Something like the following psuedo-code:

```lua
local TSM_API = TSM_API

if TSM_API and TSM_API.IsUIVisible("CRAFTING") then
    RM_Window:SetPoint("TOPLEFT" TSM frame name, "TOPRIGHT")
else
     -- TSM is not enabled or displaying Blizzard's crafting UI
     RM_Window:SetPoint("TOPLEFT", Blizzard crafting UI name, "TOPRIGHT")
end
```

Depending on the settings in Recipe Master, "TOPLEFT" and "TOPRIGHT" could be user preferences, allowing the user to dock RM to either the left or right of TSM.

**Comment by BrenoLudgero** [comment]
The presence of TSM is now properly handled. Also, when TSM is present, the Recipe Master window is moveable and vertically resizable. The changes have been implemented in the latest version (Vanilla 1.0.3), which is now available for download.
Thank you for your suggestion, @Myrroddin !
