### ISSUE TITLE
Compatibility with CloudyTradeSkill

### ISSUE THREAD

**Issue by Konsafloof** [BrenoLudgero/Recipe_Master#21]
**Is your feature request related to a problem? Please describe.**
Recipe Master overlaps a few CloudyTradeSkills buttons

**Describe the solution you'd like**
Moving Recipe Master over a few pixels to not overlap CloudyTradeSkills buttons

**Describe alternatives you've considered**

**Additional context**
![WowClassic_tmYNd7B5M7](https://github.com/user-attachments/assets/e6549cee-129f-438a-908c-b6e0ec7344c4)

**Comment by Konsafloof** [comment]
> Hello, @Konsafloof.
> 
> I'm assuming that this is the "Hotfix" upload by GrumpyPlayers, is that correct?

Yes

**Comment by BrenoLudgero** [comment]
No worries ;)

This issue will be worked on ASAP and fixed on the next update. Thank you!
