### ISSUE TITLE
Not being displayed with TSM's crafting window

### ISSUE THREAD

**Issue by Larsy93** [BrenoLudgero/Recipe_Master#22]
**Describe the bug**
doesnt work wit tsm in classic, does not show up when opening the profession.

**Game version**
vanilla

**To Reproduce**
Example steps to reproduce the behavior:
1. Open cooking (tsm interface)
2. no recipe master

**Comment by BrenoLudgero** [comment]
Hello, @Larsy93.

![screen](https://github.com/user-attachments/assets/7b63260c-99c3-4ebc-98d9-328173139889)

Please, ensure that Recipe Master is currently installed by opening your AddOn list:

![screen01](https://github.com/user-attachments/assets/398b4c4b-4113-460b-9ec8-e64779315387)

If Recipe Master is not listed, double check if you installed the [Vanilla version](https://www.curseforge.com/wow/addons/recipe-master/files/all?page=1&pageSize=20&gameVersionTypeId=67408) of Recipe Master.

**Comment by Larsy93** [comment]
Hmm, really weird, it works perfectly with Skillet and the vanilla UI. But with TSM it doesnt show up for me. If I press the "wowui" button in TSM it works there, but never with the TSM frame. Both addons latest version and no .lua errors in the bugsack.

**Comment by BrenoLudgero** [comment]
I see. Could you please disable all add-ons except Recipe Master and TSM to test if the problem persists?

**Comment by BrenoLudgero** [comment]
@Larsy93 Could you please disable all add-ons except Recipe Master and TSM to test if the problem persists?
