### ISSUE TITLE
Occasional tooltip error

### ISSUE THREAD

**Issue by Erebril** [BrenoLudgero/Recipe_Master#23]
**Describe the bug**
Getting a tooltip error

/RecipeMaster/Source/Handlers/TooltipHandler.lua:96: attempt to index local 'currentLineText' (a nil value)

**Game version**
Fresh Classic Aniversary

**To Reproduce**
Mage Character lvl 10 in Forjas. Whit Enchanting and Tailoring
Other addons: 
-Skillet Classic
-Loom Bis Tooltips
-Profession Assistance
-Accountant
-Ala TradeSkills
-Disenchater Plus

**Screenshots**
![imagen](https://github.com/user-attachments/assets/fcfb8723-9088-46fd-8f73-da86f9310b45)

**Additional context**

**Comment by BrenoLudgero** [comment]
Hello, @Erebril.

Thank you for the detailed description!

I'll work on this immediately.

**Comment by BrenoLudgero** [comment]
@Erebril Is it a specific item that triggers this error or is it triggered by any recipe?

When it triggers, is from mousing over a recipe icon contained in Recipe Master's window, another add-on's window or somewhere else?

**Comment by Erebril** [comment]
It happend when hovering a recipe. the one from the picture. ItemID : 2889
![imagen](https://github.com/user-attachments/assets/89e59544-4b9f-492a-a2c7-bde9accba540)

But i logged in again and didn't happend .... idk!!

**Comment by BrenoLudgero** [comment]
Right. Just one last question: 

When the error pops up, will it trigger again if you mouse over the same recipe?

**Comment by Erebril** [comment]
yes, when i got the error, happend everytime i hover over the recipe.

**Comment by BrenoLudgero** [comment]
I wasn't able to reproduce this issue with this or any other recipe, but, I'll add a check to at least prevent this error from coming up.

Thank you for opening this issue and the additional help!
