### ISSUE TITLE
Trainer recipes not included in the database

### ISSUE THREAD

**Issue by justaround31** [BrenoLudgero/Recipe_Master#3]
Hello,

Certain recipes are not showing eg Elixir of Greater Agility, which is obtained from trainer at 240 skill.
![RM Alch](https://github.com/BrenoLudgero/Recipe_Master/assets/166156292/3807437a-7f68-419b-a72c-cb7e1f5f7aee)

**Comment by BrenoLudgero** [comment]
Hello, @justaround31.

The aim of Recipe Master is to assist you in identifying and keeping track of recipes that are not readily available like the trainer recipes.

Those can be included in the database in the future, but the immediate priority is to display the recipes' sources.

**Comment by BrenoLudgero** [comment]
Every craftable item / learnable spell for each profession is now part of the database in Version 2.2.0.

Thank you @justaround31 for the feedback!
