### ISSUE TITLE
SoD - Unobtainable recipes are still listed as "learnable".

### ISSUE THREAD

**Issue by Ruuubi** [BrenoLudgero/Recipe_Master#5]
It seems like in Season of Discovery the "Greater Mystic Wand" item (from enchanting) got an update and the old one was removed.
The old recipe will always be displayed as "learnable" even tho it can no longer be obtained from the trainer - only the new version can be learned.
Not sure if it's possible to exclude old recipes from the list so they no longer show up.

Old wand: https://www.wowhead.com/classic/item=11290/greater-mystic-wand
New wand: https://www.wowhead.com/classic/item=217287/greater-mystic-wand

New recipe is already known - older recipe is still listed as "learnable", yet unobtainable.
![greater_mystic_wand](https://github.com/user-attachments/assets/16cdeb36-cc73-4755-8d78-50fc226c071a)

**Comment by BrenoLudgero** [comment]
Hello, @Ruuubi!
Thank you for providing all the details on this issue!
I'll add some logic to the Wowhead scraper to handle situations like this.
A new version will soon be available with an updated database!

**Comment by tanrak** [comment]
This problem also occurs in the Cataclysm version. And it only appears in the profession of enchanting.

**Comment by BrenoLudgero** [comment]
Hello, @tanrak.
Are you referring to occurrences of two recipes with the same name?

**Comment by tanrak** [comment]
Sorry, maybe it's not quite the same problem as mentioned above. In principle, it can be said that not all recipes are recognized as learned. Here is a screenshot with two examples. You can also see this from the total number of recipes learned, which is far too low for the level.
![enchanting_recipemaster](https://github.com/user-attachments/assets/2d8ce50b-9c35-4a99-96e2-958ec6da6d55)

**Comment by BrenoLudgero** [comment]
@tanrak Please leave a comment on the newly created issue #8 so we can further work on it.
